### DISCUSSION TITLE
Unexpected Widget Rebuild with Hot Reload After Adding auto_route

### DISCUSSION THREAD

**Discussion by Mir1001** [Milad-Akarie/auto_route_library#1999] [Q&A] [answered]
After adding the excellent library `auto_route` to my test project (pages start and second), I noticed unexpected behavior with Flutter's hot reload. Even when I am on the second page and press "Hot reload," (even without any change) all widgets are refreshed (as seen in the debug console). Also if I am on second page, I have notice strange rebuild order starts with main, second than at the end start page. 

```bash
I/flutter (17433): MyApp On hot reload every time. Why?
I/flutter (17433): MySecondPage only this is expected to reload if bottom text has been changed
I/flutter (17433): MyStartPage On hot MyStartPage reload every time. Why?
```

**Is this expected behavior, and how can I prevent it?**

Thanks...

main.dart

```dart
import 'package:auto_route/auto_route.dart';
import 'package:basicflutter/app_router.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

final _appRouter = AppRouter();

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of application.
  @override
  Widget build(BuildContext context) {
    print("MyApp On hot reload every time. Why?");
    return MaterialApp.router(
      routerConfig: _appRouter.config(),
    );
  }
}

@RoutePage()
class MyStartPage extends StatelessWidget {
  const MyStartPage({super.key});
  static const routeName = '/start';
  @override
  Widget build(BuildContext context) {
    print("MyStartPage On hot MyStartPage reload every time. Why?");
    return Scaffold(
      appBar: AppBar(
        title: Text('Stateless Scaffold with Button '),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            context.router.push(MySecondRoute(title: 'Flutter Second Page')); //fix as suggested by [Milad-Akarie](https://github.com/Milad-Akarie)
            //Navigator.push(
            //  context,
            //  MaterialPageRoute(
            //      builder: (context) =>
             //         const MySecondPage(title: 'Flutter gggg Page')),
            //);
            // Define the action when the button is pressed
            print('Button Pressed1');
          },
          child: Text('Press Me'),
        ),
      ),
    );
  }
}

@RoutePage()
class MySecondPage extends StatefulWidget {
  const MySecondPage({super.key, required this.title});
  static const routeName = '/second';
  final String title;

  @override
  State<MySecondPage> createState() => _MySecondPageState();
}

class _MySecondPageState extends State<MySecondPage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    print(
        "MySecondPage only this is expected to reload if bottom text has been changed");
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the this many times x:',
            ),
            Text(
              '$_counter',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

app_router.dart

```dart
import 'package:auto_route/auto_route.dart';
import 'app_router.gr.dart';
import 'main.dart';

@AutoRouterConfig(replaceInRouteName: 'Page,Route')
class AppRouter extends $AppRouter {
  @override
  List<AutoRoute> get routes => [
        /// routes go here
        /// @RoutePage()
        AutoRoute(page: MyStartRoute.page, initial: true),
        AutoRoute(page: MySecondRoute.page, path: MySecondPage.routeName),
      ];
}
```

pubspec.yaml

```yaml
name: basicflutter
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_route: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  auto_route_generator: ^8.1.0
flutter:
  uses-material-design: true

```
