### ISSUE TITLE
InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

### ISSUE THREAD

**Issue by Yarikml** [Milad-Akarie/auto_route_library#1008]
Hello, I'm trying to use auto_route. I got this exceptions dirung 
`flutter pub run build_runner build 
`
`>InconsistentAnalysisException: Requested result might be inconsistent with previously returned results
`
Thats my pubscpec.yaml

```
dependencies:
  auto_route: ^3.2.4
dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.8
```

Thats an error example 

```
[SEVERE] auto_route_generator:autoRouteGenerator on lib/common/app_contols_style.dart:
InconsistentAnalysisException: Requested result might be inconsistent with previously returned results
```

My config file 

```
import 'package:auto_route/annotations.dart';
import 'package:features/init/presentation/pages/auth_page.dart';
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(page: AuthPage, initial: true),
  ]
)
class $Routes{}

```
