### ISSUE TITLE
auto_route_generator conflicts with objectbox_generator

### ISSUE THREAD

**Issue by alextarana** [Milad-Akarie/auto_route_library#1086]
I have faced an issue about a conflict with objectbox_generator caused by auto_route_generator as described in https://github.com/objectbox/objectbox-dart/issues/424.

I tried some workaround such as writing a `build.yaml` file as below:
```
targets:
  $default:
    builders:
      objectbox_generator|generator:
        options:
          required_inputs: [".freezed.dart"]
      auto_route_generator|autoRouteGenerator:
        options:
          runs_before:
            - objectbox_generator:generator
```

My solution doesn't work as expected.

Any suggestions?
