### ISSUE TITLE
Rename autoRouteGenerator to auto_route_generator in build.yaml

### ISSUE THREAD

**Issue by vasilich6107** [Milad-Akarie/auto_route_library#1104]
In order to speedup codegen it is useful to add rule to project `build.yaml` to limit the file being crawled by analyzer - like

```yaml
      auto_route_generator:autoRouteGenerator:
        generate_for:
          include:
            - lib/routes/router.dart
```

More info here - https://codewithandrea.com/tips/speed-up-code-generation-build-runner-dart-flutter/

If the user writes 

```yaml
      auto_route_generator:
```

The config will not be applied cause the syntax is `[package_name]:[generator_name]`.

So each user will have to look inside the build yaml - https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route_generator/build.yaml#L2 to see the name of the generator `autoRouteGenerator`

In case if we rename `autoRouteGenerator` to `auto_route_generator` it will not affect the package but will make build.yaml config more obvious like

```yaml
      auto_route_generator:
        generate_for:
          include:
            - lib/routes/router.dart
```
