### ISSUE TITLE
Changing The Output Directory

### ISSUE THREAD

**Issue by alkebuware** [Milad-Akarie/auto_route_library#1107]
Hi Everyone,

Has anyone had success changing the output directory of auto_route's .gr.dart file. I'd like to keep all my generated files in a different part of the directory tree. I took a look at source_gen's README, and came up with the following changes to my build.yaml based on how `source_gen|combining_builder` works. But the .gr.dart always gets generated in the same directory as its annotation file.

```yaml
targets:
  $default:
    builders:
      auto_route_generator|autoRouteGenerator:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/gen/{{}}.gr.dart'
```
