### ISSUE TITLE
How to define settings in build.yaml for auto_route?

### ISSUE THREAD

**Issue by Erthela** [Milad-Akarie/auto_route_library#1336]
After run
`$ flutter pub run build_runner build`
Error: 
```
[SEVERE] auto_route_generator:autoRouteGenerator on lib/navigation/app_router.dart:

Route must have either a page or a redirect destination
```
with build.yaml
```yaml
targets:
  $default:
    sources:
      include:
        - lib/**/bloc/**.dart
        - lib/**/models/**/**.dart
        - lib/**/models/**.dart
        - lib/network/error_response.dart
        - lib/**/data/api_repo/**.repo.dart
        - lib/**/data/api_repo/**_repo.dart
        - lib/navigation/app_router.dart
        - $package$
        - lib/$lib$
    builders:
      freezed:
        generate_for:
          include:
            - lib/**/**_state.dart
            - lib/**/**_event.dart
            - lib/**/models/**/**.dart
            - lib/**/models/**.dart
      chopper_generator:
        generate_for:
          include:
            - lib/**/**.repo.dart
            - lib/**/data/api_repo/**_repo.dart
      auto_route_generator:autoRouteGenerator:
        generate_for:
          include:
            - lib/navigation/app_router.dart
      json_serializable|json_serializable:
        generate_for:
          include:
            - lib/**/models/**/**.dart
        options:
          explicit_to_json: true
          checked: true
```
app_router.dart (class for auto_route)
```dart
/*some imports*/
part 'app_router.gr.dart';

@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      page: SplashPage,
      initial: true,
      path: AppPath.empty,
    ),
    /*some more pages*/
  ],
)
class MainRouter extends _$MainRouter {}
```
