### ISSUE TITLE
PageRouteInfo does not contain 'path' getter 

### ISSUE THREAD

**Issue by kleyos** [Milad-Akarie/auto_route_library#1430]
```
dependencies:
  auto_route: ^6.0.1

dev_dependencies:
  auto_route_generator: ^6.0.0
  build_runner: ^2.1.4
```
`AutoRoute(path: 'feed', page: RunClubFeedRoute.page),`

in generated file 
```
/// generated route for
/// [RunClubFeedPage]
class RunClubFeedRoute extends PageRouteInfo<void> {
  const RunClubFeedRoute({List<PageRouteInfo>? children})
      : super(
          RunClubFeedRoute.name,
          initialChildren: children,
        );

  static const String name = 'RunClubFeedRoute';

  static const PageInfo<void> page = PageInfo<void>(name);
}
```
class PageRouteInfo does not contain path getter. But from the doc `A PageRouteInfo object will be generated for every declared AutoRoute, These objects hold path information plus strongly-typed page arguments which are extracted from the page's default constructor. `
