### ISSUE TITLE
The method 'config' isn't defined for the type 'AppRouter'.

### ISSUE THREAD

**Issue by Abdallah-al-hallak** [Milad-Akarie/auto_route_library#1441]
_appRouter.config(),
  The method 'config' isn't defined for the type 'AppRouter'.
Try correcting the name to the name of an existing method, or defining a method named 'config'.

**Comment by Milad-Akarie** [comment]
@Abdallah-al-hallak are you sure you're using v6+ version?

**Comment by Sharkigamers** [comment]
Having the same problem.

Here my pubspec.lock
```
auto_route_generator:
    auto_route:
    dependency: "direct main"
    description:
      name: auto_route
      sha256: // hide sha
      url: "https://pub.dev"
    source: hosted
    version: "6.0.5"
```
