### ISSUE TITLE
Navigator key in generated constructor declaration  in $AppRouter is wrong

### ISSUE THREAD

**Issue by arjundevlucid** [Milad-Akarie/auto_route_library#1475]
Wrong generated **$AppRouter** 
```dart 
abstract class $AppRouter extends _i14.RootStackRouter {
  $AppRouter({super.navigatorKey});
}
```
Error : **No associated named super constructor parameter.
Try changing the name to the name of an existing named super constructor parameter, or creating such named parameter.**

**Right one should be**
```dart
abstract class $AppRouter extends _i14.RootStackRouter {
  $AppRouter({navigatorKey});
}
```
**Auto route version**:
```yaml
dependencies:
  auto_route: ^6.1.0
dev_dependencies:
  auto_route_generator: ^6.1.0
```

```flutter
Flutter SDK : 3.7.10

```
