### ISSUE TITLE
[Docs] CustomRoute document.

### ISSUE THREAD

**Issue by cogivn** [Milad-Akarie/auto_route_library#1480]
Hi, 

Can you help update the [**CustomRouteBuilder**](https://github.com/Milad-Akarie/auto_route_library#custom-route-builder) documentation or has any example about it in version 6.1.0? 
In my case want to call specific page from external library using auto_route library. 

For example:
External lib:
- SocialPage

App project:
```dart
class DemoApp extends StatelessWidget {
  const DemoApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      child: ElevatedButton(
        onPressed: () {
          context.router.push(SocialRoute());
        },
        child: const Text('open new page'),
      ),
    );
  }
}
```
Thank you,

**Comment by Milad-Akarie** [comment]
Hey @cogivn your use-case is not related to using `CustomRouterBuilder` it's not used for such cases. 

They easiest way to do this is to have your external library generate it's own router then use it in the root router like follows:

```dart
class RootRouter extends $RootRouter{
 final externalRouter = ExternalRouter();

  @override
  pagesMap => { ...super.pagesMap,  ...externalRouter.pagesMap};

  @override
  routes: [

  // root routes
    ...externalRouter.routes
]
   ]

} 
```

**Comment by cogivn** [comment]
Hi @Milad-Akarie,

Thank you for replying to me. I followed your suggestion and configured the `build.yaml`. However, it seems that the example project cannot generate the file, but the files in the plugin module can be generated.
Here is my example repository: https://github.com/cogivn/auto_route_example

I configured for the `build.yaml`.
```yaml
targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator: # this for @RoutePage
        options:
          enable_cached_builds: true
        generate_for:
          - lib/**_page.dart
          - example/lib/**_page.dart
      auto_route_generator:auto_router_generator: # this for @AutoRouterConfig
        options:
          enable_cached_builds: true
        generate_for:
          - lib/**_router.dart
          - example/lib/**_router.dart
```          

External lib:
```dart
import 'package:auto_route/auto_route.dart';

import 'external_router.gr.dart';

@AutoRouterConfig(replaceInRouteName: 'Page,Route')
class ExternalRouter extends $ExternalRouter {
  @override
  List<AutoRoute> get routes => [
        AutoRoute(page: SocialRoute.page, path: '/'),
      ];
}
```
```dart
import 'package:auto_route/annotations.dart';
import 'package:flutter/material.dart';

@RoutePage()
class SocialPage extends StatelessWidget {
  const SocialPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

```

and the example files:
```dart
import 'package:auto_route/auto_route.dart';

import 'demo_router.gr.dart';

@AutoRouterConfig(replaceInRouteName: 'Page,Route')
class DemoRouter extends $DemoRouter {
  @override
  List<AutoRoute> get routes => [];
}

```
```dart
import 'package:auto_route/annotations.dart';
import 'package:flutter/material.dart';

@RoutePage()
class DemoPage extends StatelessWidget {
  const DemoPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

```
