### ISSUE TITLE
AutoRoute Helper Not compatible with IntelliJ IDEA 2023.1.2

### ISSUE THREAD

**Issue by rmasarovic** [Milad-Akarie/auto_route_library#1570]
Hi is possible update plugin for new version?
Not compatible with the version of your running IDE (IntelliJ IDEA 2023.1.2)

**Comment by Milad-Akarie** [comment]
@rmasarovic version 0.1.5 is pending approval
https://github.com/Milad-Akarie/auto_route_library/blob/master/tools/AutoRoute-Helper-0.1.5.jar

**Comment by paakjis** [comment]
@Milad-Akarie 
I'm on 2022.2.1 Patch 2. 
AutoRoute Helper 0.1.5.

Its installed I can see the helper buttons, but they do nothing when clicking them.

Do I have to wait for a new version ?

**Comment by Milad-Akarie** [comment]
@paakjis this issue is supposed to be fixed in 0.1.5, please share your router setup

**Comment by paakjis** [comment]
@Milad-Akarie 
Its similar to [example project ](https://github.com/Milad-Akarie/auto_route_library/tree/master/auto_route/example)

Auto Router works fine, just the Helper doesn't do anything.

PS.
_I wanted to launch your example project, to test if it works there, but it says:
Your Flutter application is created using an older version of the Android embedding. It is being deprecated in favor of Android embedding v2. To migrate your project, follow the steps at:_

pubspec.yaml

```
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  hooks_riverpod: ^2.3.6
  firebase_database: ^10.2.2
  firebase_core: 2.13.1
  hive_flutter:
  auto_route: ^7.4.0
  google_sign_in: ^6.1.4
  firebase_auth: ^4.6.2
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  json_serializable:
  build_runner:
  flutter_gen_runner:

  auto_route_generator: ^7.1.1


## Install derry from https://pub.dev/packages/derry and run derry build, derry watch, derry gen
scripts: derry.yaml

flutter:

  uses-material-design: true

```

/lib/router/router.dart

```
part 'router.gr.dart';

@AutoRouterConfig(replaceInRouteName: 'Screen,Route')
class AppRouter extends _$AppRouter {
  @override
  List<AutoRoute> get routes => [
        AutoRoute(path: '/', page: HomeRoute.page, children: [
          RedirectRoute(path: '', redirectTo: 'list'),
          AutoRoute(
            path: 'list',
            page: ListTab.page,
            maintainState: true,
            children: [
              AutoRoute(
                path: '',
                page: ListRoute.page,
                title: (ctx, _) => 'List',
              ),
            ],
          ),
          AutoRoute(
            path: 'map',
            page: MapTab.page,
            children: [
              AutoRoute(path: '', page: MapRoute.page),
            ],
          ),
          AutoRoute(
            path: 'profile',
            page: ProfileTab.page,
            children: [
              AutoRoute(path: '', page: ProfileRoute.page),
            ],
          ),
        ]),
        AutoRoute(page: SignInRoute.page, path: '/signIn'),
        RedirectRoute(path: '*', redirectTo: '/'),
      ];
}

@RoutePage(name: 'ListTab')
class ListTabScreen extends AutoRouter {
  const ListTabScreen({super.key});
}

@RoutePage(name: 'MapTab')
class MapTabScreen extends AutoRouter {
  const MapTabScreen({super.key});
}

@RoutePage(name: 'ProfileTab')
class ProfileTabScreen extends AutoRouter {
  const ProfileTabScreen({super.key});
}
```

Anything else I should provide?
