### ISSUE TITLE
Add support for `source_gen|combining_builder`

### ISSUE THREAD

**Issue by Wouter12** [Milad-Akarie/auto_route_library#1674]
Is it possible to add support in auto_route_generator for :
```yaml
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_map_literal
            - ...
      auto_route_generator:auto_router_generator:
        ...
```
I recently upgraded to v7, and i'm using the part builder. In my code I disabled the analyzer for all generated files. However, i run into issues where screens are not imported in the `router.dart` file, but my analyzer does not complain about this.

I changed the exclude to also analyze `**.gr.dart` files, however, now i'm getting complaints about the `implicit_dynamic_map_literal` in the generated code.

[source_gen](https://pub.dev/packages/source_gen#quick-start-guide-for-writing-a-generator) has support for this, where every generator package built upon source_gen can also add an ignore for the analyzer codes mentioned in the build.yaml.

Is it possible to add support for this in auto_route_generator?

**Comment by Milad-Akarie** [comment]
@Wouter12  do you just need a way to add custom ignore_for_file rules?

**Comment by Wouter12** [comment]
Yes, but from what I gather out of the `source_gen` documentation, they already provide an API to allow for extra `ignore_for_files` comments in the generated files

**Comment by Milad-Akarie** [comment]
@Wouter12 ya so implementing a similar thing should do the trick right?

**Comment by Milad-Akarie** [comment]
@Wouter12 If what you're thinking is utilizing the same list you pass to the combining builder that's nearly impossible because `AutoRouteGenerator` has nothing to do with combining builders, even when it's used with a part-file directive, that just makes it mimic how `SharedPartBuilders` work.

**Comment by Milad-Akarie** [comment]
@Wouter12 this feature is added to the new release
```yaml
auto_route_generator:auto_router_generator:
   options: 
       ignore_for_file: 
         - custom-rule1
         - custom-rule2
```
