### ISSUE TITLE
Specifying output location gives an error

### ISSUE THREAD

**Issue by jimsnab** [Milad-Akarie/auto_route_library#1686]
I am trying to specify the output path in `build.yaml`

```
targets:
  $default:
    builders:
      auto_route_generator|auto_router_generator:
        generate_for:
          - lib/routes/{{}}.dart
        options:
          build_extensions:
            '^lib/routes/{{}}.dart': 'lib/routes/generated/{{}}.gr.dart'
```

The result is

`Invalid argument(s): Configured build_extensions should be a map from inputs to outputs.`

I guess it's not supported? Or am I doing something wrong?

**Comment by jonpittock** [comment]
Hi I can confirm this is an issue. Looking at the source code it seems as if that is by design?

Any word if this is going to be supported?

**Comment by jonpittock** [comment]
Here is my current config. Notice that I have had to comment out the build_extensions

```yaml
      #autoroute @AutoRouterConfig()
      auto_route_generator:auto_router_generator:
        enabled: true
        generate_for:
          - lib/src/**_router.dart  #limit to specific file suffix
        options:
          enable_cached_builds: true #experimental
      #          #not currently supported by autoroute
      #          build_extensions:
      #            '^lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generated/{{file}}.gr.dart'

      
      #autoroute @RoutePage()
      auto_route_generator:auto_route_generator:
        enabled: true
        generate_for:
          - lib/src/**_route.dart #limit to specific file suffix
        options:
          enable_cached_builds: true #experimental
      #          #not currently supported by autoroute
      #          build_extensions:
      #            '^lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generated/{{file}}.gr.dart'
```

Here is a useful link describing the process to allow this (in general)
https://simonbinder.eu/posts/build_directory_moves/

At the bottom:

### Tips for builder authors
If you're writing a builder, you should consider making your outputs configurable so that users can choose which files your builder generates. If you're writing a shared part builder for source_gen, there's nothing more you have to do - it just works already.

For other builders, first stop using hard-coded outputs. You may be using something like buildStep.input.changeExtension() to construct an output today. As users configure your builder, this stops working! Instead, use the [allowedOutputs](https://pub.dev/documentation/build/latest/build/BuildStep/allowedOutputs.html) getter on BuildStep. If you know you'll only have a single output, you can use allowedOutputs.single.

Next, you can make outputs configurable and parse them from BuilderOptions in your factory. You can take a look at the [implementation in source_gen](https://github.com/dart-lang/source_gen/blob/6ad4a7d0f4694243c15c1480ea3290b05b9043f9/source_gen/lib/builder.dart#L28-L82) for inspiration.
