### ISSUE TITLE
build_runner - Missing library material

### ISSUE THREAD

**Issue by FufferKS** [Milad-Akarie/auto_route_library#1859]
Hi, I recently started trying to optimise my build_runner. 
Something tipped of intermittent failures. On CI, from clean state, most succeed, but some report this error:
```
[SEVERE] auto_route_generator on lib/features/subscriptions/presentation/subscriptions_page.dart:

Invalid argument(s): Missing library: package:flutter/material.dart
```

It might be due to a rule I've added to `build.yaml`:
```
      auto_route_generator:
        generate_for:
          include:
            - lib/**routing**.dart
            - lib/**page**.dart
```
But I am not 100% sure since the problem is non deterministic.

I'm running on:
```
  injectable: 2.3.2
  injectable_generator: 2.4.1
  analyzer: 5.13.0
  flutter: 3.13.9
```
