### ISSUE TITLE
Version solving failed on auto_route: ^8.0.0 and auto_route_generator: ^7.3.2

### ISSUE THREAD

**Issue by chuong-pivot** [Milad-Akarie/auto_route_library#1901]
Hi, i'm running `flutter pub get` on a newly created project and got this error while trying to use auto route:
```
Resolving dependencies... 
Because auto_route_generator >=7.3.2 depends on auto_route ^7.8.4 and
  auto_route_research depends on auto_route ^8.0.0, auto_route_generator >=7.3.2 is
  forbidden.
So, because auto_route_research depends on auto_route_generator ^7.3.2, version solving
  failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on auto_route: flutter pub add auto_route:^7.9.2
```

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.4 23E214 darwin-arm64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

pubspec.yaml:
```
name: auto_route_research
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_route: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
```

Please take a look, thank you.
