### ISSUE TITLE
Page argument mismatch

### ISSUE THREAD

**Issue by DevNico** [Milad-Akarie/auto_route_library#319]
The generated route file has the type dynamic instead of the actual type of the page argument.

```dart
class CreatePage extends StatelessWidget {
  final Test test;

  CreatePage({Key key, this.test}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class CreateRoute extends _i1.PageRouteInfo {
  CreateRoute({this.key, this.test}) : super(name, path: '/create');

  CreateRoute.fromMatch(_i1.RouteMatch match)
      : key = null,
        test = null,
        super.fromMatch(match);

  final _i8.Key key;

  final dynamic test;

  static const String name = 'CreateRoute';
}

@override
final Map<String, _i1.PageFactory> pagesMap = {
  CreateRoute.name: (entry) {
      var route = entry.routeData.as<CreateRoute>();
      return _i1.MaterialPageX(entry: entry, child: _i4.CreatePage(key: route.key, test: route.test));
    },
};
```

I would expect the type to match the argument type in the page.

**Comment by Milad-Akarie** [comment]
@DevNico That's the main goal of AutoRoute.. are you sure you're doing everything right? did you try with a different model?

**Comment by DevNico** [comment]
Alright so I've retested it and it works with my freezed models as intended but I get the result mentioned above with my sqfentity generated database models.

**Comment by Milad-Akarie** [comment]
@DevNico  The build.dart file inside of .dart_tool/builds/entrypoint/build.dart should show you the order, please share it.

**Comment by Milad-Akarie** [comment]
this might work...haven't tried it yet
create a **build.yaml** file next to **pubspec.yaml** and put this code inside of it.

```yaml
# disable the builder from the lib
targets:
  $default:
    builders:
      autoRouteGenerator:
        enabled: false

# declare a local one with required_inputs set to .g.dart
builders:
  autoRouteGenerator:
    import: "package:auto_route_generator/builder.dart"
    builder_factories: ["autoRouteGenerator"]
    build_extensions: {'.dart': ['.gr.dart']}
    required_inputs: [".g.dart"]
    auto_apply: dependents
    build_to: source
```

let me know if it works!
