### ISSUE TITLE
Default Parameter {Key key = const Key('')} - Method not found: 'Key'

### ISSUE THREAD

**Issue by jlnrrg** [Milad-Akarie/auto_route_library#444]
There seems to be an import issue when defining default Keys on a Page's Widget.

<details>
<summary>pubspec.yaml</summary>

```yaml

dependencies:
  auto_route: ^1.0.2

dev_dependencies:
  auto_route_generator: ^1.0.2
  build_runner: ^1.12.2
```
</details>

<details>
<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)

• No issues found!
```
</details>

#### error message

```
lib/views/router/router_try.gr.dart:102:28: Error: Method not found: 'Key'.
      {_i8.Key key = const Key('Test'),
                           ^^^
```

#### router_try.gr.dart

```dart
DancerProfileEditPageRoute(
      {_i8.Key key = const Key('Test')}) ...
}
```
