### ISSUE TITLE
change auto_route version

### ISSUE THREAD

**Issue by magician20** [Milad-Akarie/auto_route_library#526]
I'm trying to change auto route version from auto_route: ^1.0.2 to latest version auto_route: ^2.2.0
But I got this build error:

> The current Dart SDK version is 2.12.3.
>     Because no versions of auto_route_generator match >1.0.2 <2.0.0 and auto_route_generator <=1.0.0-beta.11 depends on source_gen ^0.9.0, auto_route_generator <1.0.0-∞ or >1.0.2 <2.0.0-∞ requires source_gen ^0.9.0.
> 
>     And because auto_route_generator >=1.0.0 <1.0.2 depends on source_gen ^0.9.10+3, auto_route_generator <1.0.2-∞ or >1.0.2 <2.0.0-∞ requires source_gen ^0.9.0.
>     And because auto_route_generator >=2.0.0 depends on code_builder ^4.0.0 and chopper_generator >=4.0.0-nullsafety.0 depends on source_gen ^1.0.0, if chopper_generator >=4.0.0-nullsafety.0 and auto_route_generator <1.0.2-∞ or >1.0.2 then code_builder ^4.0.0.
> 
> (1) So, because chopper_generator >=0.1.0 <3.0.5 depends on logging ^0.11.0 and chopper_generator <0.1.0 requires SDK version >=2.0.0-dev <2.0.0, if auto_route_generator <1.0.2-∞ or >1.0.2 and chopper_generator <3.0.5-∞ or >=4.0.0-nullsafety.0 then code_builder ^4.0.0 or logging ^0.11.0.
> 
>     Because chopper_generator >=4.0.0-nullsafety.0 depends on code_builder ^3.7.0 and chopper_generator <0.1.0 requires SDK version >=2.0.0-dev <2.0.0, chopper_generator <0.1.0-∞ or >=4.0.0-nullsafety.0 requires code_builder ^3.7.0.
> 
>     And because chopper_generator >=0.1.0 <3.0.5 depends on logging ^0.11.0, chopper_generator <3.0.5-∞ or >=4.0.0-nullsafety.0 requires code_builder ^3.7.0 or logging ^0.11.0.
> 
>     And because if auto_route_generator <1.0.2-∞ or >1.0.2 and chopper_generator <3.0.5-∞ or >=4.0.0-nullsafety.0 then code_builder ^4.0.0 or logging ^0.11.0 (1), if auto_route_generator <1.0.2-∞ or >1.0.2 and chopper_generator <3.0.5-∞ or >=4.0.0-nullsafety.0 then logging ^0.11.0.
> 
>     And because chopper_generator >=3.0.5 <4.0.0-nullsafety.0 depends on logging ^0.11.4, if auto_route_generator <1.0.2-∞ or >1.0.2 and chopper_generator any then logging ^0.11.0.
> 
>     Because no versions of chopper match >4.0.0-nullsafety.1 <5.0.0 and chopper 4.0.0-nullsafety.1 depends on logging ^1.0.0, chopper ^4.0.0-nullsafety.1 requires logging ^1.0.0.
> 
>     Thus, one of chopper ^4.0.0-nullsafety.1 or auto_route_generator <1.0.2-∞ or >1.0.2 or chopper_generator any must be false.
> 
>     And because auto_route_generator 1.0.2 depends on auto_route ^1.0.2, if chopper ^4.0.0-nullsafety.1 and chopper_generator any and auto_route_generator any then auto_route ^1.0.2.
>     And because todo_list_app depends on both auto_route ^2.2.0 and chopper ^4.0.0-nullsafety.1, chopper_generator is incompatible with auto_route_generator.
> 
>     So, because todo_list_app depends on both auto_route_generator any and chopper_generator any, version solving failed.
> pub get failed (1;     So, because todo_list_app depends on both auto_route_generator any and chopper_generator any, version solving failed.)

pubspec.yaml File:
```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^2.2.0
  connectivity: ^3.0.3
  freezed_annotation: ^0.14.1
  dartz: ^0.10.0-nullsafety.1
  rxdart: ^0.27.0
  flutter_bloc: ^7.0.0
  get_it: ^7.1.3
  injectable: ^1.4.0
  chopper: ^4.0.0-nullsafety.1
  flutter_secure_storage: ^4.2.0
  built_value: ^8.0.6
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 
  build_runner: 
  freezed: 
  injectable_generator:
  json_serializable: 
  chopper_generator:
  built_value_generator:
```

At the moment, I am still using the older version 1.0.2

Thanks.
