### ISSUE TITLE
Change extension of generated file

### ISSUE THREAD

**Issue by markokosticdev** [Milad-Akarie/auto_route_library#658]
This configuration is not working for changing the extension
Is it possible to change extension of the generated file?

build.yaml
```
builders:
  auto_route_generator:
    import: "package:auto_route_generator/builder.dart"
    builder_factories: [ "autoRouteGenerator" ]
    build_extensions: {".dart": [".config.dart"]}
```
