### ISSUE TITLE
auto_route_generator generates file with error

### ISSUE THREAD

**Issue by alex461919** [Milad-Akarie/auto_route_library#707]
In my `main.dart` :

```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(page: MyHomePage, initial: true),
  ],
)
class $AppRouter {}
```

In the generated file `main.gr.dart` :

```dart
class AppRouter extends \_i1.RootStackRouter {
AppRouter([_i2.GlobalKey<_i2.NavigatorState>? navigatorKey])
: super(navigatorKey);

@override
final Map<String, \_i1.PageFactory> pagesMap = {
    MyHomeRoute.name: (routeData) => \_i1.MaterialPageX<dynamic>(
//                                        ^^^^^^^^^^^^^
//The named parameter 'child' is required, but there's no corresponding argument.
//Try adding the required argument.

        routeData: routeData,
        builder: (data) {
//      ^^^^^^^
//The named parameter 'builder' isn't defined.
         final args = data.argsAs<MyHomeRouteArgs>();
           return _i3.MyHomePage(key: args.key, title: args.title);
        })

};

...
```

`pubspec.yaml`:

```yaml
environment:
sdk: ">=2.12.0 <3.0.0"

dependencies:
flutter:
sdk: flutter
cupertino_icons: ^1.0.2
auto_route: ^2.4.0

dev_dependencies:
auto_route_generator: ^2.1.0
build_runner: ^2.1.2
flutter_test:
sdk: flutter
```

What am I doing wrong ?

**Comment by Milad-Akarie** [comment]
Upgrade auto_route_generator to 2.4.0

**Comment by alex461919** [comment]
Thanks!

**Comment by joeldegerman99** [comment]
@Milad-Akarie I have the exact same issue! I need to use the version before 2.4.0, which is 2.1.0 for the generator if i am not wrong and auto route 2.2.1.

I am using flutter 2.2.3 and can't migrate to flutter 2.5.1 anytime soon. Why does it not generate correct code?

**Comment by arkeri** [comment]
> @Milad-Akarie I have the exact same issue! I need to use the version before 2.4.0, which is 2.1.0 for the generator if i am not wrong and auto route 2.2.1.
> 
> I am using flutter 2.2.3 and can't migrate to flutter 2.5.1 anytime soon. Why does it not generate correct code?

Same here because other dependencies have conflicts with 2.4.0 and many haven't updated to flutter 2.5.1 yet.

**Comment by PatrykIZajac** [comment]
> @Milad-Akarie I have the exact same issue! I need to use the version before 2.4.0, which is 2.1.0 for the generator if i am not wrong and auto route 2.2.1.
> 
> I am using flutter 2.2.3 and can't migrate to flutter 2.5.1 anytime soon. Why does it not generate correct code?

Same situation, any solution @Milad-Akarie  ?  Flutter : 2.2.3

**Comment by madtocc** [comment]
@joeldegerman99 @arkeri @PatrykIZajac 
I guess the issue is that it is pointing to the most recent version... I faced the same issue today, not sure if you fixed or not but I had to make it work... I did a quick workaround (revert commits & update dependencies) to make it work, probably not the best solution but it works... 
if you guys can try out just point to the branch I have created:
on your dependencies:
```
auto_route:
    git:
      url: https://github.com/madtocc/auto_route_library.git
      ref: hotfix/flutter_2.2.3
      path: auto_route/
```

and on your dev_dependencies:

```
auto_route_generator:
    git:
      url: https://github.com/madtocc/auto_route_library.git
      ref: hotfix/flutter_2.2.3
      path: auto_route_generator/
```
