### ISSUE TITLE
Problem when running "flutter packages pub run build_runner watch / build"

### ISSUE THREAD

**Issue by ben55j** [Milad-Akarie/auto_route_library#832]
Hello, 

I am looking for to push a new screen from my HomePage. 
So I  configured my router this way: 

<img width="577" alt="Capture d’écran 2021-11-15 à 20 19 09" src="https://user-images.githubusercontent.com/7754473/141841003-c9411862-c07f-4b16-a56f-3b4b802a27ad.png">

But each time I am running the command "**flutter packages pub run build_runner watch**" or "**flutter packages pub run build_runner build**"
It gave me this error. Can you help please ?
<img width="1168" alt="Capture d’écran 2021-11-15 à 20 17 40" src="https://user-images.githubusercontent.com/7754473/141840838-01f7031a-941e-48d8-a54f-1f59019de2fe.png">
?

**Comment by Agondev** [comment]
Add this override to your pubspec until @Milad-Akarie fixes these

```yaml
dependency_overrides:
  auto_route:
    git:
      url: https://github.com/Agondev/auto_route_library
      path: auto_route
```

**Comment by ben55j** [comment]
Hello @Agondev ! Thank you for your fast reply. I've added your override to my pubspec, but the problem is unchanged.
I did make a "flutter clean" and get package without any success :(
See below extract of my pubspec with the overrides.
<img width="527" alt="Capture d’écran 2021-11-15 à 20 42 07" src="https://user-images.githubusercontent.com/7754473/141843773-8c3845cc-08d8-4753-9804-06a42270cd5f.png">

**Comment by Agondev** [comment]
> Hello @Agondev ! Thank you for your fast reply. I've added your override to my pubspec, but the problem is unchanged. I did make a "flutter clean" and get package without any success :( See below extract of my pubspec with the overrides. <img alt="Capture d’écran 2021-11-15 à 20 42 07" width="527" src="https://user-images.githubusercontent.com/7754473/141843773-8c3845cc-08d8-4753-9804-06a42270cd5f.png">

First of all, it's a yaml file. Indentations are first class citizens.

Second, saying "problem is unchanged" tells me nothing -- provide the actual error.

Third, don't use screenshots of code. Copy paste the code into code blocks.

**Comment by ben55j** [comment]
Hello, 
Yes, sorry for that. I've adjusted the Indentations of the override, and it did download the packages.
Now when I am running the command `"flutter packages pub run build_runner watch"` i get this message:

`Package "build_runner" is not an immediate dependency.
Cannot run executables in transitive dependencies.
pub finished with exit code 65 `

**Comment by Agondev** [comment]
Show your entire pubspec.

And generally, always specify package version.

**Comment by ben55j** [comment]
Here my entire pubspec.yaml
-----------------------------------
name: adom
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  auto_route: ^2.2.0
  responsive_builder: ^0.4.1
  auto_route_generator: ^2.1.0
  feather_icons: ^1.1.0-nullsafety.0
  font_awesome_flutter: ^9.0.0-nullsafety
  flutter_staggered_grid_view: ^0.4.0
  url_launcher: ^6.0.3
  layout: ^0.6.2
  carousel_slider: ^4.0.0
  dots_indicator: ^2.0.0
  animated_text_kit: ^4.2.1
  visibility_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
    auto_route:
      git:
        url: https://github.com/Agondev/auto_route_library
        path: auto_route

build_runner:

  # auto_route_generator: ^2.1.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by Agondev** [comment]
Wrap that in a code block like so:

\```yaml 
CODE HERE
\```

**Comment by ben55j** [comment]
Thank you for the advice, I didn't know that. Here the yaml file: 
```yaml
name: adom
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  auto_route: ^2.2.0
  responsive_builder: ^0.4.1
  auto_route_generator: ^2.1.0
  feather_icons: ^1.1.0-nullsafety.0
  font_awesome_flutter: ^9.0.0-nullsafety
  flutter_staggered_grid_view: ^0.4.0
  url_launcher: ^6.0.3
  layout: ^0.6.2
  carousel_slider: ^4.0.0
  dots_indicator: ^2.0.0
  animated_text_kit: ^4.2.1
  visibility_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
    auto_route:
      git:
        url: https://github.com/Agondev/auto_route_library
        path: auto_route

build_runner:

  # auto_route_generator: ^2.1.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

**Comment by Agondev** [comment]
Change this:

```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
    auto_route:
      git:
        url: https://github.com/Agondev/auto_route_library
        path: auto_route

build_runner:
```

To this:

```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5

dependency_overrides:
  auto_route:
    git:
      url: https://github.com/Agondev/auto_route_library
      path: auto_route
```

Pay close attention to my changes and memorize this flow.
