### ISSUE TITLE
Duplicate PRs regarding broking change in Flutter 2.8

### ISSUE THREAD

**Issue by Agondev** [Milad-Akarie/auto_route_library#841]
@Milad-Akarie 

#839 
#756 
#712 
#669 

Are all duplicates that fix the breaking change in Flutter 2.8

My PR #834 in addition to fixing the duplicates also addresses linter errors and accounts for latest version 3.1.3 and generator 3.1.0

**Comment by mrseth01** [comment]
I have had to keep a local copy of your library for a while now, and then fixing merge issues with each update. Please merge this.

**Comment by Chinmay-KB** [comment]
This PR is necessary for auto route to work on Flutter 2.8. #878 . Kindly merge this soon

**Comment by Moujarkash** [comment]
when you are going to merge this pull request, it's important for flutter 2.8.0

**Comment by Agondev** [comment]
> This PR is necessary for auto route to work on Flutter 2.8. #878 . Kindly merge this soon


For now you can add this to your pubspec:

```yaml
dependency_overrides:
  auto_route:
    git:
      url: https://github.com/Agondev/auto_route_library
      path: auto_route
```
