### ISSUE TITLE
Problem with router.push(newPage ())

### ISSUE THREAD

**Issue by ben55j** [Milad-Akarie/auto_route_library#902]
Hello,

For passing arguments, I am trying to push a new page using `router.push(NewPage (argument))` , but I got the following error on my console: 
`The argument type 'SearchPage' can't be assigned to the parameter type 'PageRouteInfo<dynamic>.`
It works well with `context.router.pushNamed('/mypath')` but I would prefer previous method for passing argument...

Any Idea of what's going wrong ?

Here the code of the page I am trying to push: 

```dart
import 'package:flutter/material.dart';

class SearchPage extends StatefulWidget {
  final String zipcode;

  const SearchPage({this.zipcode = ""});
  @override
  _SearchPageState createState() => _SearchPageState();
}

class _SearchPageState extends State<SearchPage> {
  
  @override
  Widget build(BuildContext context) {
   
    return Scaffold(
        body: Center(child: Container(child: Text("SearchPage: ${widget.zipcode}"),)));
  }

}

```

And the call I wrote for pushing this page: 
```dart
  context.router.push(SearchPage(zipcode: "75000"));
```

Also,  here my pubspec.yaml file

```yaml
name: website_adom
description: Website for Adom Services App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  auto_route: ^3.1.3
  responsive_builder: ^0.4.1
  auto_route_generator: ^3.1.0
  feather_icons: ^1.1.0-nullsafety.0
  font_awesome_flutter: ^9.0.0-nullsafety
  flutter_staggered_grid_view: ^0.4.0
  url_launcher: ^6.0.3
  layout: ^1.0.2
  carousel_slider: ^4.0.0
  dots_indicator: ^2.0.0
  animated_text_kit: ^4.2.1
  visibility_detector: ^0.2.0
  get: ^4.3.8
  webviewx: ^0.2.1
  cloud_firestore: ^2.3.0
  firebase_core: ^1.3.0
  awesome_dialog: ^2.1.0
  string_validator: ^0.3.0
  intl: ^0.17.0
  firebase_auth: ^2.0.0
  webview_flutter: ^2.0.13
  google_tag_manager: ^0.1.0
  seo_renderer: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:

  uses-material-design: true
  assets:
    - assets/images/

```

And my flutter doctor: 

`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6.1 20G224 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (1 available)

• No issues found!
`

Thank you for your help!
Benjamin
